{
 "title": "money talks v1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Hours Saved with Automation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_hours_saved",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Money Saved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_money_saved",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Job Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_run_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_run_failure",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}