{
 "title": "Red Hat Summit 2025",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "SWIM Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Switch Upgrade Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM main_unifiedjob WHERE (status = 'successful' AND unified_job_template_id = 46) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Failed Switch Upgrade Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM main_unifiedjob WHERE (status = 'failed' AND unified_job_template_id = 46) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Automation Hours Saved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_hours_saved",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Engineer Money Saved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "prefix: $" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_money_saved",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Longterm Financial Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Initial Investment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Estimated YTD ROI",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ansible_job_template_roi_calc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estimated 3yr ROI",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_job_template_roi_prediction",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent to Break Even",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/200000)*100", "type": "math" }
   ]
  }
 ]
}