---
- name: Install components for Promethueus and Grafana
  hosts: fedora01
  # hosts: localhost

  tasks:
    - name: Perform Prometheus install
      ansible.builtin.include_role:
        name: update_prom_config
